name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build macOS app
      run: npm run electron-pack
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: luna-app-mac
        path: dist/*.dmg